
name: Docs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linters:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install python packages and dependencies
        run: |
          sudo apt update
          sudo apt install -y libapt-pkg-dev intltool
      - name: Make docs
        run: |
          make docs
